### ISSUE TITLE
Add more Javascript programs in the existing repo. 

### ISSUE THREAD

**Issue by Abhijay007** [Abhijay007/Javascript-Practice-programs#1]
you can add any program related to the concepts of javascript.  Anything that can help beginners to learn the concepts of javascript

**Comment by codeR49** [comment]
i want to contribute to it

**Comment by Abhijay007** [comment]
> i want to contribute to it

Go ahead and add any program you like and make a pull request. Good luck !!

**Comment by eidoriantan** [comment]
@Abhijay007 Would you mind adding `hacktoberfest` in the list of topics on this project to participate on [Hacktoberfest 2020](https://hacktoberfest.digitalocean.com/)?

I would love to add a simple program to contribute on [Hacktoberfest 2020](https://hacktoberfest.digitalocean.com/).

Thanks!

**Comment by Geekz45679** [comment]
Hello, I have added a program, see: https://github.com/Abhijay007/Javascript-Practice-programs/pull/6

**Comment by dhapin** [comment]
Check my program, #12

**Comment by bratinkundu** [comment]
Please check this, #9

**Comment by Abhijay007** [comment]
> Please check this, #9

ok

**Comment by Geekz45679** [comment]
Hello, I have added another program, see PR https://github.com/Abhijay007/Javascript-Practice-programs/pull/18

**Comment by Dilshan97** [comment]
#21

**Comment by codeR49** [comment]
not able to push changes to my forked repo, permission denied

**Comment by codeR49** [comment]
kindly check my pull request #22

**Comment by pallavithakare28** [comment]
Hey, @Abhijay007 I have added a countdown timer program. Please check my PR [#23](https://github.com/DSC-RSU/DSC-RSU-Website/pull/23).

**Comment by Avninder99** [comment]
i want to contribute

**Comment by Avninder99** [comment]
Please Check my Pull Request #25

**Comment by Dilshan97** [comment]
Please check my pull request #42
