### ISSUE TITLE
Add contributors to the Existing Readme.md file

### ISSUE THREAD

**Issue by Abhijay007** [Abhijay007/Javascript-Practice-programs#19]
Add contributors to the Existing Readme.md file with proper profile pic and Github profiles.
add this above MIT licence

**Comment by muchirijane** [comment]
Hey @Abhijay007 , can I work on this issue.

**Comment by Abhijay007** [comment]
> Hey @Abhijay007 , can I work on this issue.

Yeah sure!!

**Comment by muchirijane** [comment]
I will try it with a Github action, hope it will work.

**Comment by Abhijay007** [comment]
issue resolved
