### ISSUE TITLE
update readme.md for better understanding of concept

### ISSUE THREAD

**Issue by Abhijay007** [Abhijay007/Javascript-Practice-programs#2]
update readme.md for better understanding of the concept. Add a table of contents or anything you like that me it more understandable

**Comment by Cheemashyper** [comment]
Hello @Abhijay007 ,
I would like to work on this issue,
Kindly assign this to me & I will begin working on it right away!

**Comment by b-farhaan** [comment]
I have updated the readme file, can I make the pull request?

**Comment by Abhijay007** [comment]
> I have updated the readme file, can I make the pull request?

Yeah sure!!

**Comment by Cheemashyper** [comment]
Hello @Abhijay007 
I have created a Pull Request, Kindly Check it out and let me know.
If you think it is good then Merge .

Cheers,
Ck Cheema

**Comment by b-farhaan** [comment]
@Abhijay007 
I have made the changes and created a pull request. Please have a look and let me know if you want any further changes

**Comment by Abhijay007** [comment]
issue resolved

**Comment by Abhijay007** [comment]
issue resolved
