### ISSUE TITLE
Add Hacktoberfest as a topic in your repository

### ISSUE THREAD

**Issue by muchirijane** [Abhijay007/Javascript-Practice-programs#26]
@Abhijay007 Hey, for the repository to be part of the hacktoberfest you need to add it as a topic. Click the settings where you add a description to the repo and you will a section below it where you can add the topic hacktoberfest, hackbtoberfest2020 as tags.

**Comment by Abhijay007** [comment]
issue resolved

**Comment by muchirijane** [comment]
Awesome 👍🏽

**Comment by muchirijane** [comment]
One more thing. make recently closed or open Prs (were part of the hacktoberfest issue) with the `hacktoberfest-accepted` label for them to count. 
For more details, you can check the new rules updated in the  official website => https://hacktoberfest.digitalocean.com/hacktoberfest-update   
You have a great project.🥇
