### ISSUE TITLE
Add more javascript-Practice-programs for beginners

### ISSUE THREAD

**Issue by Abhijay007** [Abhijay007/Javascript-Practice-programs#27]
Add more javascript-Practice-programs that help beginners to understand the concepts

**Comment by Priya19999** [comment]
Can I please work on this issue

**Comment by Abhijay007** [comment]
> Can I please work on this issue

Yeah sure!!

**Comment by geekyboy14** [comment]
@Abhijay007 made a PR #28 for JS dates and neap year program. Please check and merge. Thanks in advance :)

**Comment by Priya19999** [comment]
Made a PR for JS guess game. Do give it a check. Thanks.

**Comment by kratikasinghal** [comment]
@Abhijay007 Can I work on this issue?

**Comment by Abhijay007** [comment]
> @Abhijay007 Can I work on this issue?

Yeah sure!! go ahead
Happy hacking 😊

**Comment by Avninder99** [comment]
@Abhijay007 I would like to work on this, Can i try ?

**Comment by RiyaMadaan** [comment]
@Abhijay007  I made a PR #30 for basic programs for beginners. Please check and merge. Thanks.

**Comment by reverk** [comment]
@Abhijay007 Can I do this? I'd like to make cm to m converter.

**Comment by GriffinMLN** [comment]
Hey! I hope I can contribute here. Want to add a beginner friendly "rock, paper, scissors" game.

**Comment by Abhijay007** [comment]
> Hey! I hope I can contribute here. Want to add a beginner friendly "rock, paper, scissors" game.

Yeah !! go for it but please make that program with vanilla javascript don't use any library like bootstrap or jquery because this repository is for beginners to help them understand the concepts of javascript. The use of such libraries may confuse them.

When you are done with the writing of code make a PR.

Till then Happy hacking 😊!!

**Comment by ParthSaini-2006** [comment]
Made a PR #45 , a small js program to help beginners in taking user input and performing functions. Please check and Merge @Abhijay007 

Thankyou

**Comment by GriffinMLN** [comment]
> > Hey! I hope I can contribute here. Want to add a beginner friendly "rock, paper, scissors" game.
> 
> Yeah !! go for it but please make that program with vanilla javascript don't use any library like bootstrap or jquery because this repository is for beginners to help them understand the concepts of javascript. The use of such libraries may confuse them.
> 
> When you are done with the writing of code make a PR.
> 
> Till then Happy hacking 😊!!

No problem, PR #44 is definitely only vanilla HTML/JavaScript!

**Comment by Dilshan97** [comment]
Please check my pull request #46

**Comment by Dilshan97** [comment]
Please check my pull request #47

**Comment by Dilshan97** [comment]
Please check my pull request #47
